events/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name='events'


urlpatterns = [
    path('', views.EventListView.as_view()),
    path('events', views.EventListView.as_view(), name='all'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event/create',
        views.EventCreateView.as_view(success_url=reverse_lazy('events:all')), name='event_create'),
    path('event/<int:pk>/update',
        views.EventUpdateView.as_view(success_url=reverse_lazy('events:all')), name='event_update'),
    path('event/<int:pk>/delete',
        views.EventDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_delete'),
    path('event_picture/<int:pk>', views.stream_file, name='event_picture'),
    path('event/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='event_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('events')), name='event_comment_delete'),
    path('event/<int:pk>/important',
    views.AddImportantView.as_view(), name='event_important'),
    path('event/<int:pk>/unimportant',
    views.DeleteImportantView.as_view(), name='event_unimportant'),
    path('event/news',
    views.sendNewsData, name='event_news'),
    path('event/hotels',
    views.sendHotels, name='event_hotels'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view() ),
]

olympics/events/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name='events'


urlpatterns = [
    path('', views.EventListView.as_view()),
    path('events', views.EventListView.as_view(), name='all'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event/create',
        views.EventCreateView.as_view(success_url=reverse_lazy('events:all')), name='event_create'),
    path('event/<int:pk>/update',
        views.EventUpdateView.as_view(success_url=reverse_lazy('events:all')), name='event_update'),
    path('event/<int:pk>/delete',
        views.EventDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_delete'),
    path('event_picture/<int:pk>', views.stream_file, name='event_picture'),
    path('event/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='event_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('events')), name='event_comment_delete'),
    path('event/<int:pk>/important',
    views.AddImportantView.as_view(), name='event_important'),
    path('event/<int:pk>/unimportant',
    views.DeleteImportantView.as_view(), name='event_unimportant'),
]

olympics/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('', include('home.urls')),
    path('eventapis/', include('eventapis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

events/forms.py
from django import forms
from events.models import Event, Athlete
from django.core.files.uploadedfile import InMemoryUploadedFile
from events.humanize import naturalsize


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'


    class Meta:
        model = Event
        fields = ['name', 'stadium','event_at', 'picture']


    def clean(self) :
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None : return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")


    def save(self, commit=True) :
        instance = super(CreateForm, self).save(commit=False)

        f = instance.picture
        if isinstance(f, InMemoryUploadedFile):
            bytearr = f.read();
            instance.content_type = f.content_type
            instance.picture = bytearr

        if commit:
            instance.save()

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

events/views.py
from events.models import Event, Comment, Imp, Athlete, Participation
from events.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from events.forms import CreateForm, CommentForm
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from events.utils import dump_queries
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

from django.core.files.uploadedfile import InMemoryUploadedFile

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from json import dumps
import requests

class EventListView(OwnerListView):
    model = Event

    template_name = "events/event_list.html"
    def get(self, request) :
        event_list = Event.objects.all()
        important = list()
        if request.user.is_authenticated:
            rows = request.user.important_events.values('id')
            important = [ row['id'] for row in rows ]

        strval =  request.GET.get("search", False)
        if strval :
            query = Q(name__contains=strval)
            query.add(Q(stadium__contains=strval), Q.OR)
            objects = Event.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :
            objects = Event.objects.all().order_by('-updated_at')[:10]

        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'event_list0' : event_list, 'important': important, 'event_list' : objects, 'search': strval}
        retval = render(request, self.template_name, ctx)

        dump_queries()
        return retval;


class EventDetailView(OwnerDetailView):
    model = Event
    template_name = "events/event_detail.html"
    #athletes = list()
    def get(self, request, pk) :
        x = Event.objects.get(id=pk)
        comments = Comment.objects.filter(event=x).order_by('-updated_at')
        comment_form = CommentForm()
        #rows = request.x.athlete_list.values('id')
        athletes = Participation.objects.filter(event=x)

        #athletes = Participation.objects.filter(event=x)
        context = { 'event' : x, 'comments': comments, 'comment_form': comment_form, 'athlete_list': athletes }
        return render(request, self.template_name, context)


class EventCreateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('events:all')
    def get(self, request, pk=None) :
        form = CreateForm()
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        event = form.save(commit=False)
        event.owner = self.request.user
        event.save()
        return redirect(self.success_url)


class EventUpdateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('events:all')
    def get(self, request, pk) :
        event = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(instance=event)
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        event = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=event)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        event = form.save(commit=False)
        event.save()

        return redirect(self.success_url)


class EventDeleteView(OwnerDeleteView):
    model = Event


def stream_file(request, pk) :
    event = get_object_or_404(Event, id=pk)
    response = HttpResponse()
    response['Content-Type'] = event.content_type
    response['Content-Length'] = len(event.picture)
    response.write(event.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        e = get_object_or_404(Event, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, event=e)
        comment.save()
        return redirect(reverse('events:event_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "events/comment_delete.html"

    def get_success_url(self):
        event = self.object.event
        return reverse('events:event_detail', args=[event.id])


@method_decorator(csrf_exempt, name='dispatch')
class AddImportantView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Event, id=pk)
        imp = Imp(user=request.user, event=t)
        try:
            imp.save()
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteImportantView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Event, id=pk)
        try:
            imp = Imp.objects.get(user=request.user, event=t).delete()
        except Imp.DoesNotExist as e:
            pass

        return HttpResponse()



def sendNewsData(request):

    receive = requests.get('https://newsapi.org/v2/top-headlines?country=us&category=sports&apiKey=2680777f2b434adc879881bd3f666169')
    dataDictionary = receive.json()['articles']

    dataJSON = dumps(dataDictionary)
    return render(request, 'events/event_news.html', {'data': dataJSON})


def sendHotels(request):

    url = "https://hotels4.p.rapidapi.com/locations/v2/search"

    querystring = {"query":"new york","locale":"en_US","currency":"USD"}

    headers = {
        'x-rapidapi-host': "hotels4.p.rapidapi.com",
        'x-rapidapi-key': "0c32763019mshee9f7664ff5e966p1ec273jsncd47401bf285"
        }

    receive = requests.request("GET", url, headers=headers, params=querystring)
    # print(receive.json())
    dataDictionary = receive.json()['suggestions'][1]['entities']

    dataJSON = dumps(dataDictionary)
    return render(request, 'events/event_hotels.html', {'data': dataJSON})

olympics/events/views.py
from events.models import Event, Comment, Imp, Athlete, Participation
from events.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from events.forms import CreateForm, CommentForm
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from events.utils import dump_queries
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

from django.core.files.uploadedfile import InMemoryUploadedFile


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


class EventListView(OwnerListView):
    model = Event

    template_name = "events/event_list.html"
    def get(self, request) :
        event_list = Event.objects.all()
        important = list()
        if request.user.is_authenticated:
            rows = request.user.important_events.values('id')
            important = [ row['id'] for row in rows ]

        strval =  request.GET.get("search", False)
        if strval :

            query = Q(name__contains=strval)
            query.add(Q(stadium__contains=strval), Q.OR)
            objects = Event.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else :

            objects = Event.objects.all().order_by('-updated_at')[:10]

        for obj in objects:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'event_list0' : event_list, 'important': important, 'event_list' : objects, 'search': strval}
        retval = render(request, self.template_name, ctx)

        dump_queries()
        return retval;





class EventDetailView(OwnerDetailView):
    model = Event
    template_name = "events/event_detail.html"
    #athletes = list()
    def get(self, request, pk) :
        x = Event.objects.get(id=pk)
        comments = Comment.objects.filter(event=x).order_by('-updated_at')
        comment_form = CommentForm()
        #rows = request.x.athlete_list.values('id')
        athletes = Participation.objects.filter(event=x)

        #athletes = Participation.objects.filter(event=x)
        context = { 'event' : x, 'comments': comments, 'comment_form': comment_form, 'athlete_list': athletes }
        return render(request, self.template_name, context)


class EventCreateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('events:all')
    def get(self, request, pk=None) :
        form = CreateForm()
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        event = form.save(commit=False)
        event.owner = self.request.user
        event.save()
        return redirect(self.success_url)


class EventUpdateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('events:all')
    def get(self, request, pk) :
        event = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(instance=event)
        ctx = { 'form': form }
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None) :
        event = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=event)

        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template_name, ctx)

        event = form.save(commit=False)
        event.save()

        return redirect(self.success_url)


class EventDeleteView(OwnerDeleteView):
    model = Event


def stream_file(request, pk) :
    event = get_object_or_404(Event, id=pk)
    response = HttpResponse()
    response['Content-Type'] = event.content_type
    response['Content-Length'] = len(event.picture)
    response.write(event.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        e = get_object_or_404(Event, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, event=e)
        comment.save()
        return redirect(reverse('events:event_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "events/comment_delete.html"

    def get_success_url(self):
        event = self.object.event
        return reverse('events:event_detail', args=[event.id])


@method_decorator(csrf_exempt, name='dispatch')
class AddImportantView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Event, id=pk)
        imp = Imp(user=request.user, event=t)
        try:
            imp.save()
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteImportantView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Event, id=pk)
        try:
            imp = Imp.objects.get(user=request.user, event=t).delete()
        except Imp.DoesNotExist as e:
            pass

        return HttpResponse()

events/templates/events/athlete_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Athlete List</h1>
  {% if athlete_list %}
  <ul>
    {% for athlete in athlete_list %}
      <li>
          <h4><b>{{ athlete.first_name }}
          {{ athlete.last_name }}</b></h4>
          <p>
          {{ athlete.gender }} || {{ athlete.age }}
          </p>
          <p>
          {{ athlete.country }}
          </p>

      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no athletes in this event.</p>
  {% endif %}

  <p>
    <a href="{% url 'events:all' %}">Back to Event List</a>
  </p>
{% endblock %}

events/templates/events/comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'events:event_detail' comment.event.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Event</h1>

<p>Are you sure you want to delete the event: {{ event }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

events/templates/events/event_detail.html
{% extends "base_menu.html" %}
{% load humanize %}
{% block head %}
<style>
  .overlay{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0,0,0,0.5); /*dim the background*/
  }
</style>
{% endblock %}
{% block content %}
{% if event.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'events:event_picture' event.id %}">
</div>
{% endif %}

<span style="float: right;">
({{ event.updated_at|naturaltime }})
{% if event.owner == user %}
<a href="{% url 'events:event_update' event.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'events:event_delete' event.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ event.name }}</h1>
{% if event.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'events:event_picture' event.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ event.stadium }}
</p>
<p>
{{ event.area }}
</p>
<p>
{{ event.event_at }}
</p>

<p>
</p>
<h3>Athlete List</h3>
{% if athlete_list %}
<ul>
  {% for athlete in athlete_list %}
    <li>
        <h4><b>{{ athlete.first_name }}
        {{ athlete.last_name }}</b></h4>
        <p>
        {{ athlete.athlete }} || {{ athlete.country }}
        </p>
        

    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no athletes in this event.</p>
{% endif %}

<p>
<a href="{% url 'events:all' %}">All events</a>
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'events:event_comment_create' event.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Events" onclick="window.location.href='{% url 'events:all' %}';return false;">
</form>
</p>
{% endif %}
<p><h4>Comments</h4></p>
{% for comment in comments %}
<p> {{ comment.text }}</p>
<p>
      --  {{comment.owner}}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'events:event_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
{% endblock %}

events/templates/events/event_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'events:all' %}';return false;">
  </form>
</p>

<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

events/templates/events/event_hotels.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Hotels</h1>
<div style="width: 80%;
    border: 1px solid black;
    background-color: lightcyan;
    font-family: Helvetica, sans-serif;">
        <div style="margin: 5%;">

            <h4 id='neatdata'></h4>
        </div>
    </div>

<script>
    var data = JSON.parse("{{data|escapejs}}");
    //var dataNode = document.getElementById('alldata');
    //dataNode.innerHTML+="{{data|escapejs}}";
    var dataNode = document.getElementById('neatdata');
    for(var x in data){
        dataNode.innerHTML+=' -- '+'<h3>'+data[x]['name']+'</h3>'+'<br>'+data[x]['latitude']+'<br>'+data[x]['longitude']+'<br><br>';
    }
</script>
{% endblock %}

events/templates/events/event_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Events</h1>
<div style="float:right">

<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'events:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if event_list %}
<ul>
  {% for event in event_list %}
    <li>
        <a href="{% url 'events:event_detail'  event.id %}">{{ event.name }}</a>
        {% if event.owner == user %}
        (<a href="{% url 'events:event_update' event.id %}">Edit</a> |
        <a href="{% url 'events:event_delete' event.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}

        <a href="#" onclick=
            "impPost('{% url 'events:event_unimportant' event.id %}', {{ event.id }} );return false;"
            {% if event.id not in important %} style="display: none;" {% endif %}
            id="imp_star_{{event.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>

        <a href="#" onclick=
             "impPost('{% url 'events:event_important' event.id %}', {{ event.id }} );return false;"
            {% if event.id in important %} style="display: none;" {% endif %}
            id="unimp_star_{{event.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>

        <br/>
        {% endif %}
        <div style="left:10px">
            {% if event.stadium|length < 100 %}
                {{ event.stadium }}
            {% else %}
                {{ event.stadium|slice:"0:99" }}
                <a href="{% url 'events:event_detail'  event.id %}">...</a>
            {% endif %}
        </div>
        <small>
        {% if event.owner.username %}
            posted by {{ event.owner.username }}
        {% endif %}
        {{ event.natural_updated }}
        </small>

    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no events in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'events:event_create' %}">Add an Event</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'events:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'events:all' %}">Login</a>
{% endif %}
</p>
<script>
function impPost(url, event_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unimp_star_"+event_id).toggle();
        $("#imp_star_"+event_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

events/templates/events/event_news.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Event News</h1>
<div style="width: 80%;
    border: 1px solid black;
    background-color: lightcyan;
    font-family: Helvetica, sans-serif;">
        <div style="margin: 5%;">
            
            <h4 id='neatdata'></h4>
        </div>
    </div>

<script>
    var data = JSON.parse("{{data|escapejs}}");
    //var dataNode = document.getElementById('alldata');
    //dataNode.innerHTML+="{{data|escapejs}}";
    var dataNode = document.getElementById('neatdata');
    for(var x in data){
        dataNode.innerHTML+=' -- '+'<h3>'+data[x]['title']+'</h3>'+'<br><br>'+data[x]['description']+'<br><br>';
    }
</script>
{% endblock %}