events/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name='events'


urlpatterns = [
    path('', views.EventListView.as_view()),
    path('events', views.EventListView.as_view(), name='all'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event/create',
        views.EventCreateView.as_view(success_url=reverse_lazy('events:all')), name='event_create'),
    path('event/<int:pk>/update',
        views.EventUpdateView.as_view(success_url=reverse_lazy('events:all')), name='event_update'),
    path('event/<int:pk>/delete',
        views.EventDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_delete'),
    path('event_picture/<int:pk>', views.stream_file, name='event_picture'),
    path('event/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='event_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('events')), name='event_comment_delete'),
    path('event/<int:pk>/important',
    views.AddImportantView.as_view(), name='event_important'),
    path('event/<int:pk>/unimportant',
    views.DeleteImportantView.as_view(), name='event_unimportant'),
    path('event/news',
    views.sendNewsData, name='event_news'),
    path('event/hotels',
    views.sendHotels, name='event_hotels'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view() ),
]

olympics/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view() ),
]

olympics/olympics/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

olympics/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('', include('home.urls')),
    path('eventapis/', include('eventapis.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

home/models.py
from django.db import models

# Create your models here.

olympics/home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.


class HomeView(View):
    def get(self, request) :
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed' : settings.INSTALLED_APPS,
            'islocal' : islocal
        }
        return render(request, 'home/main.html', context)

olympics/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.


class HomeView(View):
    def get(self, request) :
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed' : settings.INSTALLED_APPS,
            'islocal' : islocal
        }
        return render(request, 'home/main.html', context)

olympics/home/templates/base_bootstrap.html
<!DOCTYPE html>
 <html>
  <head>

 <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>


{% load static %}

<link rel="stylesheet" href="{% static 'css/stylesheet.css'%}" type="text/css">
 <link rel="stylesheet"
     href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
     crossorigin="anonymous">

 <link rel="stylesheet"
     href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
     crossorigin="anonymous">

 <link rel="stylesheet"
     href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
         crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"crossorigin="anonymous">    </script>

   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
       crossorigin="anonymous"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
    crossorigin="anonymous"></script>

 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">



{% block head %} {% endblock %}

 </head>
<body id='every'>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

olympics/home/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>

    <ul class="nav navbar-nav">
      {% url 'events' as events %}
      <li {% if request.get_full_path == events %}class="active"{% endif %}>
          <a href="{% url 'events:all' %}">Events</a></li>
    </ul>
    <ul class="nav navbar-nav">
          <a href="{% url 'events:event_news' %}">Event News</a>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'events:event_create' %}">Create Event</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'events:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'events:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}